config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  devise_for :users

  root "home#index"

  resources :establishments, only: [:show, :edit, :update, :new, :create] do
    get 'search', on: :collection
  end
  
  concern :routes do
    post 'enabled', on: :member
    post 'disabled', on: :member
    resources :price_histories, only: [:new, :create]
    resources :portions, only: [:new, :create, :edit, :update]
  end
  
  concern :dish_tag do
    resources :dish_tags, only: [:new, :create]
  end
  
  resources :menus, only: [:index, :new, :create, :show] do 
    resources :menu_items, only: [:new, :create] do
      resources :order_items, only: [:new, :create]
    end
  end
  
  resources :dishes, only: [:index, :show, :edit, :update, :new, :create], concerns: [:routes, :dish_tag]
  resources :drinks, only: [:index, :show, :edit, :update, :new, :create], concerns: [:routes]
  resources :hours_operations, only: [:edit, :update, :new, :create]
  resources :orders, only: [:index, :new, :create, :show]
  resources :pre_registrations, only: [:index, :new, :create]
  resources :tags, only: [:new, :create]

  namespace :api do
    namespace :v1 do
      get 'orders/:establishment_code', to: 'orders#index'
      get 'orders/:establishment_code/:order_code', to: 'orders#show'
      patch 'orders/:establishment_code/:order_code', to: 'orders#update'
    end
  end
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :establishment
  has_one_attached :image
  has_many :portions, as: :portionable
  has_many :menu_items, as: :menuable
  has_many :menus, through: :menu_items
  has_many :order_items, as: :orderable
  has_many :orders, through: :order_items
  
  enum :status, { :enabled => 0, :disabled => 5 }

  validates :name, :description, :calories, presence: true
  validates :alcoholic, inclusion: { in: [true, false], message: "deve ser verdadeiro ou falso" }
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit, :new]
  before_action :set_drink_and_check_user, only: [:show, :edit, :update, :disabled, :enabled]

  def index
		@drinks = current_account.establishment.drinks
	end

  def show
		@portions = @drink.portions
	end

	def new
		@drink = Drink.new()
	end

	def create
		@drink = Drink.new(drink_params)

		if @drink.save()
			redirect_to drinks_path, notice: "Bebida cadastrada com sucesso."
		else
			flash.now[:alert] = "Bebida não cadastrada."
			render 'new'
		end
	end

	def edit;	end

	def update
		if @drink.update(drink_params)
		redirect_to drink_path(@drink.id), notice: 'Bebida atualizada com sucesso'
		else
			flash.now[:alert] = 'Não foi possível atualizar a Bebida'
			render 'edit'
		end
	end

	def disabled
		@drink.disabled!
		redirect_to @drink
	end
	
	def enabled
		@drink.enabled!
		redirect_to @drink
	end

	private

	def set_drink_and_check_user
		@drink = Drink.find(params[:id])
		if @drink.establishment.id != current_establishment.id
				return redirect_to root_path, alert: 'Você não possui acesso a essa bebida.'
		end
	end

	def drink_params
		params.require(:drink).permit(:image, :name, :description, :alcoholic, :calories, :establishment_id)
	end
end

app/views/drinks/_form.html.erb
<%= form_with(model: @drink, local: true) do |f| %>
  <div>
    <%= f.label :image %>
    <%= f.file_field :image %> 
  </div>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.check_box :alcoholic %>
    <%= f.label :alcoholic %>
  </div>
  <div>
    <%= f.label :calories %>
    <%= f.text_field :calories %>
  </div>
  <div>
    <%= f.hidden_field :establishment_id, value: current_user.establishment.id %>
  </div>
  <div><%= f.submit 'Enviar' %></div>
<% end %>

app/views/drinks/edit.html.erb
<h1>Editar Bebida</h1>

<%= render 'form' %>

<div><%= link_to 'Voltar', drink_path(current_user) %></div>

app/views/drinks/index.html.erb
<h1>Bebidas</h1>

<div>
  <%= link_to 'Cadastrar Bebida', new_drink_path %>
</div>
 <% @drinks.each do |drink| %>
  <div id=<%= dom_id(drink) %>>
    <h3><%= link_to drink.name, drink_path(drink.id) %></h3>
    <dl>
      <% if drink.image.attached? %>
        <%= image_tag drink.image, alt: "", title: "Bebida", width: "200" %>
      <% end %>
      <dt>Nome:</dt>
      <dd><%= drink.name %></dd>
      <dt>Situação da Bebida:</dt>
      <dd><%= I18n.translate(drink.status) %></dd>
    </dl>
  </div>
<% end %>

<% if @drinks.empty? %>
  <p>Não existem bebidas cadastradas</p>
<% end %>

app/views/drinks/new.html.erb
<h1>Novo Bebida</h1>

<% if @drink.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @drink.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>
<div><%= link_to 'Voltar', drinks_path %></div>

app/views/drinks/show.html.erb
<h1>Bebida</h1>

<div>
  <%= link_to 'Editar Bebida', edit_drink_path(@drink) %>
</div>
<dl>
  <% if @drink.image.attached? %>
    <%= image_tag @drink.image, alt: "", title: "Prato", width: "200" %>
  <% end %>
  <dt>Nome:</dt>
  <dd><%= @drink.name %></dd>
  <dt>Descrição:</dt>
  <dd><%= @drink.description %></dd>
  <dt>Calorias:</dt>
  <dd><%= @drink.calories %></dd>
  <dt>Alcoólico:</dt>
  <dd><%= @drink.alcoholic ? 'SIM' : 'NÃO' %></dd>
  <dt>Situação da Bebida:</dt>
  <dd><%= I18n.translate(@drink.status) %></dd>
</dl>

<div>
  <% if @drink.enabled? %>
    <%= button_to 'Desativar', disabled_drink_path(@drink.id) %>
  <% else %>
    <%= button_to 'Ativar', enabled_drink_path(@drink.id) %>
  <% end %>
</div>

<div>
  <h3>Porções</h3>
  <dl>
   <% @drink.portions.each do |portion| %>
    <dt><%= portion.description %>:</dt>
    <dd>R$ <%= portion.real %>,<%= portion.cent.to_s.rjust(2, '0') %></dd>
    <%= link_to 'Editar Porção', edit_drink_portion_path(drink_id: @drink.id, id: portion.id) %>
  <% end %>
  </dl>
</div>
<div>
  <%= link_to 'Cadastrar Porção', new_drink_portion_path(drink_id: @drink.id) %>
</div>

<h3>Histórico de Preços</h3>

<table id="price-histories">
  <thead>
    <tr>
      <th>Porções</th>
      <th>Preços</th>
      <th>Última atualização</th>
    </tr>
  </thead>
  <tbody>
  
  <% @portions.each do |portion| %>
    <% portion.price_histories.each do |price| %>
  
      <tr>
        <td><%= portion.description %></td>
        <td><%= price.real %>,<%= portion.cent.to_s.rjust(2, '0') %></td>
        <td><%= price.last_update %></td>
      </tr>
    
    <% end %>
  <% end %>
  </tbody>
</table>