config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  devise_for :users

  root "home#index"

  resources :establishments, only: [:show, :edit, :update, :new, :create] do
    get 'search', on: :collection
  end
  
  concern :routes do
    post 'enabled', on: :member
    post 'disabled', on: :member
    resources :price_histories, only: [:new, :create]
    resources :portions, only: [:new, :create, :edit, :update]
  end
  
  concern :dish_tag do
    resources :dish_tags, only: [:new, :create]
  end
  
  resources :menus, only: [:index, :new, :create, :show] do 
    resources :menu_items, only: [:new, :create] do
      resources :order_items, only: [:new, :create]
    end
  end
  
  resources :dishes, only: [:index, :show, :edit, :update, :new, :create], concerns: [:routes, :dish_tag]
  resources :drinks, only: [:index, :show, :edit, :update, :new, :create], concerns: [:routes]
  resources :hours_operations, only: [:edit, :update, :new, :create]
  resources :orders, only: [:index, :new, :create, :show]
  resources :pre_registrations, only: [:index, :new, :create]
  resources :tags, only: [:new, :create]

  namespace :api do
    namespace :v1 do
      get 'orders/:establishment_code', to: 'orders#index'
      get 'orders/:establishment_code/:order_code', to: 'orders#show'
      patch 'orders/:establishment_code/:order_code', to: 'orders#update'
    end
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :establishment
  has_one_attached :image
  has_many :portions, as: :portionable
  has_many :dish_tags, dependent: :destroy
  has_many :tags, through: :dish_tags
  has_many :menu_items, as: :menuable
  has_many :order_items, as: :orderable
  has_many :orders, through: :order_items
  
  accepts_nested_attributes_for :tags, allow_destroy: true
  
  enum :status, { :enabled => 0, :disabled => 5 }

  validates :name, :description, :calories, presence: true
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :new, :create]
  before_action :set_dish_and_check_user, only: [:show, :edit, :update, :disabled, :enabled]

  def index
		@dishes = current_account.establishment.dishes
	end

  def show
		@portions = @dish.portions
		@tags = @dish.tags
	end

	def new
		@dish = Dish.new()
		@dish.tags.build
		@tags = current_account.establishment.tags
	end

	def create
		@dish = Dish.new(dish_params)

		if @dish.save()
			redirect_to @dish, notice: "Prato cadastrado com sucesso."
		else
			flash.now[:alert] = "Prato não cadastrado."
			render 'new'
		end
	end

	def edit
		@dish.tags.build if @dish.tags.empty?
		@tags = current_account.establishment.tags
	end

	def update
		if @dish.update(dish_params)
			redirect_to @dish, notice: 'Prato atualizado com sucesso'
		else
			flash.now[:alert] = 'Não foi possível atualizar o Prato'
			render 'edit'
		end
	end

	def disabled
		@dish.disabled!
		redirect_to @dish
	end
	
	def enabled
		@dish.enabled!
		redirect_to @dish
	end

	private

	def set_dish_and_check_user
		@dish = Dish.find(params[:id])
		if @dish.establishment.id != current_establishment.id
				return redirect_to root_path, alert: 'Você não possui acesso a esse prato.'
		end
	end

	def dish_params
		params.require(:dish).permit(
			:image, 
			:name, 
			:description, 
			:calories, 
			:establishment_id, 
			tags_attributes: [:id, :establishment_id, :name, :_destroy])
	end
end

app/views/dishes/_form.html.erb
<%= form_with(model: @dish, local: true) do |f| %>
  <div>
    <%= f.label :image %>
    <%= f.file_field :image %> 
  </div>
  <div id="name_dish">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label :calories %>
    <%= f.text_field :calories %>
  </div>
  <div>
    <%= f.hidden_field :establishment_id, value: current_establishment.id %>
  </div>

  <h3>Marcadores</h3>
  <div id="tags-container">
    <%= f.fields_for :tags do |tag_form| %>
      <div class="tag-field">
        <%= tag_form.label :name, 'Marcador 1'%>
        <%= tag_form.text_field :name, placeholder: "Nome do marcador" %>
        <%= tag_form.hidden_field :establishment_id, value: current_establishment.id %>
        <%= tag_form.check_box :_destroy %>
        <%= tag_form.label :_destroy, "Remover" %>
      </div>
    <% end %>
  </div>
  
  <button type="button" onclick="addTag()">Adicionar mais uma tag</button>

  <div><%= f.submit 'Enviar' %></div>
<% end %>

<script>
  var index = 0;
  function addTag() {
    const tagsContainer = document.getElementById('tags-container');
    index = index + 1;
    const newTagDiv = document.createElement('div');
    newTagDiv.classList.add('tag-field');
    
    newTagDiv.innerHTML = `
      <label for="dish_tags_attributes_${index}_name">Marcador ${index + 1}</label>
      <input type="text" name="dish[tags_attributes][${index}][name]" 
        id="dish_tags_attributes_${index}_name" placeholder="Nome do marcador">
      <input type="hidden" name="dish[tags_attributes][${index}][id]">
      <input type="checkbox" name="dish[tags_attributes][${index}][_destroy]" id="dish_tags_attributes_${index}__destroy">
      <label for="dish_tags_attributes_${index}__destroy">Remover</label>
    `;
    
    tagsContainer.appendChild(newTagDiv);
  }
</script>

app/views/dishes/edit.html.erb
<h1>Editar Prato</h1>

<%= render 'form' %>

<div><%= link_to 'Voltar', dish_path(current_user) %></div>

app/views/dishes/index.html.erb
<h1>Pratos</h1>

<div>
  <%= link_to 'Cadastrar Prato', new_dish_path %>
</div>
 <% @dishes.each do |dish| %>
  <div id=<%= dom_id(dish) %>>
    <h3><%= link_to dish.name, dish_path(dish.id) %></h3>
    <dl>
      <% if dish.image.attached? %>
        <%= image_tag dish.image, alt: "", title: "Prato", width: "200" %>
      <% end %>
      <dt>Nome:</dt>
      <dd><%= dish.name %></dd>
      <dt>Situação do Prato:</dt>
      <dd><%= I18n.translate(dish.status) %></dd>
    </dl>
  </div>
<% end %>

<% if @dishes.empty? %>
  <p>Não existem Pratos cadastrados</p>
<% end %>

app/views/dishes/new.html.erb
<h1>Novo Prato</h1>

<% if @dish.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @dish.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

<div><%= link_to 'Voltar', dishes_path %></div>

app/views/dishes/show.html.erb
<h1>Prato</h1>

<div>
  <%= link_to 'Editar Prato', edit_dish_path(@dish) %>
</div>
<dl>
  <% if @dish.image.attached? %>
    <%= image_tag @dish.image, alt: "", title: "Prato", width: "200" %>
  <% end %>
  <dt>Nome:</dt>
  <dd><%= @dish.name %></dd>
  <dt>Descrição:</dt>
  <dd><%= @dish.description %></dd>
  <dt>Calorias:</dt>
  <dd><%= @dish.calories %></dd>
  <dt>Situação do Prato:</dt>
  <dd><%= I18n.translate(@dish.status) %></dd>
</dl>

<div>
  <% if @dish.enabled? %>
    <%= button_to 'Desativar', disabled_dish_path(@dish.id) %>
  <% else %>
    <%= button_to 'Ativar', enabled_dish_path(@dish.id) %>
  <% end %>
</div>

<div>
<div>
  <%= link_to 'Cadastrar Marcadores', new_dish_dish_tag_path(@dish) %>
</div>
<dl>
  <dt><strong>Marcadores:</strong></dt>
  <dd>
    <% @tags.each do |tag| %>
      <%= tag.name %>
    <% end %>
  </dd>
</dl>
</div>

<div>
  <h3>Porções</h3>
  <dl>
  <% @dish.portions.each do |portion| %>
    <dt><%= portion.description %>:</dt>
    <dd>R$ <%= portion.real %>,<%= portion.cent.to_s.rjust(2, '0') %></dd>
    <%= link_to 'Editar Porção', edit_dish_portion_path(dish_id: @dish.id, id: portion.id) %>
  <% end %>
  </dl>
</div>

<div>
  <%= link_to 'Cadastrar Porção', new_dish_portion_path(dish_id: @dish.id) %>
</div>

<h3>Histórico de Preços</h3>

<table id="price-histories">
  <thead>
    <tr>
      <th>Porções</th>
      <th>Preços</th>
      <th>Última atualização</th>
    </tr>
  </thead>
  <tbody>
  
  <% @portions.each do |portion| %>
    <% portion.price_histories.each do |price| %>
  
      <tr>
        <td><%= portion.description %></td>
        <td><%= price.real %>,<%= portion.cent.to_s.rjust(2, '0') %></td>
        <td><%= price.last_update %></td>
      </tr>
    
    <% end %>
  <% end %>
  </tbody>
</table>