config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  devise_for :users

  root "home#index"

  resources :establishments, only: [:show, :edit, :update, :new, :create] do
    get 'search', on: :collection
  end
  
  concern :routes do
    post 'enabled', on: :member
    post 'disabled', on: :member
    resources :price_histories, only: [:new, :create]
    resources :portions, only: [:new, :create, :edit, :update]
  end
  
  concern :dish_tag do
    resources :dish_tags, only: [:new, :create]
  end
  
  resources :menus, only: [:index, :new, :create, :show] do 
    resources :menu_items, only: [:new, :create] do
      resources :order_items, only: [:new, :create]
    end
  end
  
  resources :dishes, only: [:index, :show, :edit, :update, :new, :create], concerns: [:routes, :dish_tag]
  resources :drinks, only: [:index, :show, :edit, :update, :new, :create], concerns: [:routes]
  resources :hours_operations, only: [:edit, :update, :new, :create]
  resources :orders, only: [:index, :new, :create, :show]
  resources :pre_registrations, only: [:index, :new, :create]
  resources :tags, only: [:new, :create]

  namespace :api do
    namespace :v1 do
      get 'orders/:establishment_code', to: 'orders#index'
      get 'orders/:establishment_code/:order_code', to: 'orders#show'
      patch 'orders/:establishment_code/:order_code', to: 'orders#update'
    end
  end
end

app/models/establishment.rb
class Establishment < ApplicationRecord
  belongs_to :user
  
  has_many :dishes
  has_many :drinks
  has_many :hours_operations
  has_many :tags
  has_many :menus
  has_many :orders
  has_many :employees
  has_many :pre_registrations

  validates :brand_name, :company_name, :cnpj, :full_address, :phone, :email, :code, presence: true
  validates :phone, length: { minimum:10, maximum:11 }
  validates :code, uniqueness: true
  validate :cnpj_valid

  before_validation :generate_code

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(6).upcase if self.code.nil?
  end

  def cnpj_valid
    unless CNPJ.valid?(self.cnpj)
      self.errors.add(:cnpj, "deve ser válido")
    end
  end
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  before_action :authenticated, only: [:show]
  before_action :authenticate_user!, only: [:edit, :update, :new, :create]
  before_action :set_establishment_and_check_user, only: [:show, :edit, :update]

  def show
		@hours_operations = current_establishment.hours_operations
	end

	def search
    @dish_or_drink = params["query"]
		query = "name LIKE ? OR description LIKE ?"
    @drinks = current_establishment.drinks.where(query, "%#{@dish_or_drink}%", "%#{@dish_or_drink}%")
    @dishes = current_establishment.dishes.where(query, "%#{@dish_or_drink}%", "%#{@dish_or_drink}%")
  end

	def new
		@establishment = Establishment.new()
	end

	def create
		@establishment = Establishment.new(establishment_params)

		if @establishment.save()
			redirect_to root_path, notice: "Estabelecimento cadastrado com sucesso."
		else
			flash.now[:notice] = "Estabelecimento não cadastrado."
			render 'new'
		end
		
	end

	def edit; end

	def update
		if @establishment.update(establishment_params)
		redirect_to establishment_path(@establishment.id), notice: 'Estabelecimento atualizado com sucesso'
		else
			flash.now[:notice] = 'Não foi possível atualizar o Estabelecimento'
			render 'edit'
		end
	end

	private

	def set_establishment_and_check_user
		@establishment = Establishment.find(params[:id])
		if @establishment.id != current_establishment.id
			return redirect_to root_path, alert: 'Você não possui acesso a esse estabelecimento.'
		end
	end

	def establishment_params
		params.require(:establishment).permit(:brand_name, :company_name, :cnpj, :phone, :full_address,
			:email, :code, :user_id)
	end
  
end

app/views/establishments/_form.html.erb
<%= form_with(model: @establishment) do |f| %>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
  </div>
  <div>
    <%= f.label :company_name %>
    <%= f.text_field :company_name %>
  </div>
  <div>
    <%= f.label :cnpj %>
    <%= f.text_field :cnpj %>
  </div>
  <div>
    <%= f.label :full_address %>
    <%= f.text_field :full_address %>
  </div>
  <div>
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div><%= f.submit 'Enviar' %></div>
<% end %>

app/views/establishments/edit.html.erb
<h1>Editar Estabelecimento: <%= @establishment.code %></h1>

<%= render 'form' %>

<div><%= link_to 'Voltar', establishment_path(current_user) %></div>

app/views/establishments/new.html.erb
<h1>Novo Estabelecimento</h1>

<% if @establishment.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @establishment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/establishments/search.html.erb
<h1>Resultados da Busca por: <%= @dish_or_drink %></h1>
<p><%= @drinks.count %> <%= Drink.model_name.human(count: @drinks.count).downcase %> <%= t(:found, count: @drinks.count) %></p>
<table>
  <tr>
    <th><%= Drink.human_attribute_name(:name) %>:</th>
    <th><%= Drink.human_attribute_name(:description) %>:</th>
    <th>Ações</th>
  </tr>
  <% @drinks.each do |drink| %>
    <tr>
      <td><%= drink.name %></td>
      <td><%= drink.description %></td>
      <td><%= link_to 'Detalhe', drink_path(drink.id) %> | <%= link_to 'Editar', edit_drink_path(drink.id) %></td>
    </tr>
  <% end %>
</table>

<p><%= @dishes.count %> <%= Dish.model_name.human(count: @dishes.count).downcase %> <%= t(:found, count: @dishes.count) %></p>
<table>
  <tr>
    <th><%= Dish.human_attribute_name(:name) %>:</th>
    <th><%= Dish.human_attribute_name(:description) %>:</th>
    <th>Ações</th>
  </tr>
  <% @dishes.each do |dish| %>
    <tr>
      <td><%= dish.name %></td>
      <td><%= dish.description %></td>
      <td><%= link_to 'Detalhe', dish_path(dish.id) %> | <%= link_to 'Editar', edit_dish_path(dish.id) %></td>
    </tr>
  <% end %>
</table>

app/views/establishments/show.html.erb
<h1>Estabelecimento</h1>

<div>
  <%= link_to 'Editar Estabelecimento', edit_establishment_path(@establishment) if user_signed_in? %>
</div>
<dl>
  <dt>Dono do estabelecimento:</dt>
  <dd><%= @establishment.user.name %> | <%= @establishment.user.email %></dd>
  <dt>Código:</dt>
  <dd><%= @establishment.code %></dd>
  <dt>Nome fantasia:</dt>
  <dd><%= @establishment.brand_name %></dd>
  <dt>Nome companhia:</dt>
  <dd><%= @establishment.company_name %></dd>
  <dt>CNPJ:</dt>
  <dd><%= @establishment.cnpj %></dd>
  <dt>Endereço:</dt>
  <dd><%= @establishment.full_address %></dd>
  <dt>Telefone:</dt>
  <dd><%= @establishment.phone %></dd>
  <dt>E-mail:</dt>
  <dd><%= @establishment.email %></dd>
</dl>

<div>
  <%= link_to 'Pratos', dishes_path if user_signed_in? %>
</div>

<div>
  <%= link_to 'Bebidas', drinks_path if user_signed_in? %>
</div>

<div>
  <%= link_to 'Cadastrar Marcadores', new_tag_path if user_signed_in? %>
</div>

<dl>
  <dt><strong>Marcadores:</strong></dt>
  <dd>
    <% @establishment.tags.each do |tag| %>
      <%= tag.name %> | 
    <% end %>
  </dd>
</dl>
</div>

<div>
  <%= link_to 'Cadastrar Horário', new_hours_operation_path if user_signed_in? %>
</div>

<table>
  <thead>
    <tr>
      <th>Dia da semana</th>
      <th>Abertura</th>
      <th>Fechamento</th>
      <th>Fechado</th>
      <th><%= 'Ações' if user_signed_in? %></th>
    </tr>
  </thead>
  <tbody>
    <% @hours_operations.each do |hour| %>
      <tr>
        <td><%= I18n.translate(hour.weekday) %></td>
        <td><%= hour.opening_time.strftime("%H:%M") %></td>
        <td><%= hour.closing_time.strftime("%H:%M") %></td>
        <td><%= hour.closed ? 'Fechado' : 'Aberto' %></td>
        <td><%= link_to "editar", edit_hours_operation_path(hour.id) if user_signed_in? %></td>
      </tr>
    <% end %>
  </tbody>
</table>