config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  devise_for :users

  root "home#index"

  resources :establishments, only: [:show, :edit, :update, :new, :create] do
    get 'search', on: :collection
  end
  
  concern :routes do
    post 'enabled', on: :member
    post 'disabled', on: :member
    resources :price_histories, only: [:new, :create]
    resources :portions, only: [:new, :create, :edit, :update]
  end
  
  concern :dish_tag do
    resources :dish_tags, only: [:new, :create]
  end
  
  resources :menus, only: [:index, :new, :create, :show] do 
    resources :menu_items, only: [:new, :create] do
      resources :order_items, only: [:new, :create]
    end
  end
  
  resources :dishes, only: [:index, :show, :edit, :update, :new, :create], concerns: [:routes, :dish_tag]
  resources :drinks, only: [:index, :show, :edit, :update, :new, :create], concerns: [:routes]
  resources :hours_operations, only: [:edit, :update, :new, :create]
  resources :orders, only: [:index, :new, :create, :show]
  resources :pre_registrations, only: [:index, :new, :create]
  resources :tags, only: [:new, :create]

  namespace :api do
    namespace :v1 do
      get 'orders/:establishment_code', to: 'orders#index'
      get 'orders/:establishment_code/:order_code', to: 'orders#show'
      patch 'orders/:establishment_code/:order_code', to: 'orders#update'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "PaLeva" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to root_path do %>
      <h1 class="link">PaLeva</h1>
    <% end %>

    <nav class="container mx-auto">
      <% if user_signed_in? || employee_signed_in? %>
        <%= form_with url: search_establishments_path, method: :get do |f| %>
          <%= f.label :query, 'Buscar Pratos ou Bebidas' %>
          <%= f.text_field :query %>
          <%= f.submit 'Buscar' %>
        <% end %>
        <%= link_to 'Estabelecimento', current_establishment unless current_establishment.nil? %> |
        <%= link_to 'Cardápio', menus_path() %> |
        <%= link_to 'Pedidos', orders_path %> |
        <%= link_to 'Pré-cadastros |', pre_registrations_path if user_signed_in? %> 
        <%= current_account.email %> |
        <%= button_to 'Sair', user_signed_in? ? destroy_user_session_path : destroy_employee_session_path, method: :delete %>
  
        <%= link_to 'Finalizar Pedido', new_order_path unless session[:order_items].blank? %>
      <% else %>
        <%= link_to 'Dono', new_user_session_path %>
        <%= link_to 'Funcionário', new_employee_session_path %>
      <% end %>
    </nav>

    <main class="container mx-auto mt-28 px-5 flex">
      <div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <%= yield %>
    </main>
    
  </body>
</html>